[package]
name = "draco-nd-vector"
version.workspace = true
edition = "2021"
description = "Proc macros generating the low-dimensional vector implementations used by draco-oxide-core."
license.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
seq-macro = "0.3.6"