//! Generates one `#[test]` stub per `tests/profiles/**/*.toml`. The stub
//! delegates to this crate's `run_profile` (see `src/lib.rs`), which parses the
//! TOML and executes the operations at test time. Keeping build.rs to enumeration
//! only means parse errors surface as readable test failures rather than
//! cryptic build errors.

use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo:rerun-if-env-changed=MAX_VECTOR_DIM");

    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let profiles_root = manifest_dir.join("profiles");

    // Re-run codegen whenever the profiles tree changes. The directory entry
    // is enough for added/removed files; per-file entries cover edits and
    // anything in nested subdirectories.
    println!("cargo:rerun-if-changed=profiles");

    let mut profiles = Vec::new();
    if profiles_root.is_dir() {
        collect_profiles(&profiles_root, &profiles_root, &mut profiles);
    }
    profiles.sort_by(|a, b| a.fn_name.cmp(&b.fn_name));

    // Detect identifier collisions so the build fails with a clear message
    // instead of producing duplicate `fn` definitions.
    for w in profiles.windows(2) {
        if w[0].fn_name == w[1].fn_name {
            panic!(
                "draco-oxide profile name collision: `{}` is produced by both \
                 {} and {} — rename one of the TOML files.",
                w[0].fn_name,
                w[0].rel_path.display(),
                w[1].rel_path.display(),
            );
        }
    }

    let mut out = String::new();
    out.push_str("// Auto-generated by build.rs. Do not edit.\n");
    for p in &profiles {
        let rel = p.rel_path.to_string_lossy().replace('\\', "/");
        out.push_str(&format!(
            "#[test]\nfn {fn_name}() {{\n    \
                ::tests::run_profile(\n        \
                    \"{fn_name}\",\n        \
                    concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/profiles/{rel}\"),\n        \
                    concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/data\"),\n        \
                    concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/outputs\"),\n    \
                );\n}}\n\n",
            fn_name = p.fn_name,
            rel = rel,
        ));
    }

    let out_dir = PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR is set by cargo"));
    fs::write(out_dir.join("generated_profiles.rs"), out).expect("writing generated_profiles.rs");
}

struct ProfileFile {
    fn_name: String,
    rel_path: PathBuf,
}

fn collect_profiles(root: &Path, dir: &Path, out: &mut Vec<ProfileFile>) {
    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            // Subdirectories also need rerun-if-changed so newly added files
            // there trigger regeneration.
            println!("cargo:rerun-if-changed={}", path.display());
            collect_profiles(root, &path, out);
        } else if path.extension().and_then(|s| s.to_str()) == Some("toml") {
            println!("cargo:rerun-if-changed={}", path.display());
            let rel = path.strip_prefix(root).unwrap().to_path_buf();
            let fn_name = profile_fn_name(&rel);
            out.push(ProfileFile {
                fn_name,
                rel_path: rel,
            });
        }
    }
}

/// `foo/bar.toml` → `foo_bar`. Non-alphanumeric chars collapse to `_` so the
/// result is always a valid Rust identifier.
fn profile_fn_name(rel: &Path) -> String {
    let stem = rel.with_extension("");
    let raw = stem.to_string_lossy().replace(['/', '\\'], "_");
    let mut s: String = raw
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    if s.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        s.insert(0, '_');
    }
    s
}
