[package]
name = "nd-vector"
version = "0.0.0"
edition = "2024"
description = "Contains macros that writes low dimensional vectors implementation."
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
seq-macro = "0.3.6"